config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "lists#index"

  resources :lists do
    resources :bookmarks, except: [:destroy]
  end
  resources :bookmarks, only: [:destroy], as: 'delete_bookmark'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: {scope: :list}
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord

  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list,  only: [:new, :create, :destroy]
  before_action :set_bookmark,  only: [:destroy]

  # GET /bookmarks
  def index
    @bookmarks = Bookmark.all
  end



  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks
  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list), notice: "bookmark was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /bookmarks/1
  # def update
  #   if @bookmark.update(bookmark_params)
  #     redirect_to @bookmark, notice: "bookmark was successfully updated."
  #   else
  #     render :edit, status: :unprocessable_entity
  #   end
  # end

  # DELETE /bookmarks/1
  def destroy
    @bookmark.destroy
    redirect_to list_path(@list), notice: "bookmark was successfully destroyed."
  end


  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end


    # Only allow a bookmark of trusted parameters through.


end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :set_list, only: [ :show, :destroy]

  # GET /lists
  def index
    @lists = List.all
  end

  # GET /lists/1
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list), notice: "list was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end


  # DELETE /lists/1
  def destroy
    @list.destroy
    redirect_to lists_url, notice: "list was successfully destroyed."
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_bookmark.html.erb
<div id="<%= dom_id bookmark %>">
  <p>
    <strong>Name:</strong>
    <%= bookmark.comment %>
    <%= bookmark.movie_id %>
    <%= bookmark.list_id %>
  </p>
</div>

app/views/bookmarks/index.html.erb
<h1>Bookmarks</h1>

<div id="bookmarks">
  <% @bookmarks.each do |bookmark| %>
    <%= render bookmark %>
  <% end %>
</div>

<%= link_to "New bookmark", new_bookmark_path %>

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit class:"btn btn-primary" %>
<% end %>


<div>
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/bookmarks/show.html.erb
<%= render @bookmark %>

<div>

  <%= link_to "Back to bookmarks", list_bookmarks_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
  </div>



  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div class="co-12 col-sm-6 col-md-4 mb-3">
  <%= link_to list_path(list), class:"text-decoration-none" do %>
    <div class="card-category bg-white rounded shadow h-100 mb-4 ml-4" data-aos="zoom-in">
      <p><%= list.name %></p>
      <% if list.photo.attached? %>
        <%= cl_image_tag list.photo.key, height: 300, width: 400, crop: :fill %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/lists/_lists.html.erb
<% @lists.each do |list| %>
    <%= render list %>
  <p>
    <%= link_to "Show this list", list %>
  </p>
<% end %>

app/views/lists/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <i class="fa-solid fa-film"></i>
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">My lists</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">New list</a>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a>
            </div>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://media.lesechos.com/api/v1/images/view/62c696f7cde6181c2d44dafb/1280x720-webp/0701967133971-web-tete.webp);">
  <div class="container">
    <h1>Save any kind of movies</strong>!</h1>
  </div>
</div>

<div class="d-grid gap-2 d-md-flex justify-content-md-end me-md-2 mt-5">
<p><%= link_to "Create a movie list", new_list_path, class: "btn btn-primary pull-right"%></p>
</div>

<div class="container">
  <div class="row">
   <h1>My lists</h1>
      <% @lists.each do |list| %>
        <%= render list %>
      <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render "form", list: @list %>


<div>
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/show.html.erb
<%= link_to "Add a movie", new_list_bookmark_path(@list), class: "btn btn-success pull-right" %>
<p>
</p>

<div class="position-relative">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key %>')">
    <h1 class="text-white text-center"><%= @list.name %></h1>
  </div>
  <span class="movie-tag"><%= pluralize(@list.movies.size, "movie") %></span>
</div>

<div>
<%#   <div class="bookmarks">
    <ul>
      <% @list.bookmarks.each do |bookmark| %>
 <%#       <li><%= bookmark.comment %> <%#<%= link_to "delete bookmark", delete_bookmark_path(@list, bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure ?" } %><%#</li>
 <%#     <% end %>
 <%#   </ul>
  </div> %>

  <p><%= link_to "Back to lists", lists_path %></p>
</div>




<div class="row my-2">
    <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <div class="col-12 col-sm-6 mb-4" data-aos="zoom-in">
        <div class="bg-white rounded shadow h-100">
          <div class="p-3 rounded-bottom d-flex flex-column">
            <strong><%= movie.title %> <span class="text-muted font-weight-normal">• <%= movie.rating %> <i class="fas fa-star star-yellow"></i></span></strong>
            <small class="text-muted"><%= movie.overview %></small>
            <div class="d-flex align-items-end justify-content-between pt-4">
              <div>
                <i class="fas fa-quote-left me-2"></i><small class="flex-grow-1"><%= bookmark.comment %></small>
              </div>
              <small class="text-right flex-shrink-0"><%= link_to "delete", delete_bookmark_path(@list, bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}, class: 'text-danger' %></small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>